[[redirects]]
  from = "/*"
  to = "https://friends-again-api.herokuapp.com/api/ :splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"